export const countries = [
  { name: "India", code: "+91", iso: "in", length: 10 },
  { name: "United States", code: "+1", iso: "us", length: 10 },
  { name: "United Kingdom", code: "+44", iso: "gb", length: 10 },
  { name: "Australia", code: "+61", iso: "au", length: 9 },
  { name: "Canada", code: "+1", iso: "ca", length: 10 },
  { name: "Singapore", code: "+65", iso: "sg", length: 8 },
  { name: "United Arab Emirates", code: "+971", iso: "ae", length: 9 },
  { name: "Germany", code: "+49", iso: "de", length: 11 },
  { name: "France", code: "+33", iso: "fr", length: 9 },
  { name: "Japan", code: "+81", iso: "jp", length: 10 },
  { name: "China", code: "+86", iso: "cn", length: 11 },
  { name: "Brazil", code: "+55", iso: "br", length: 11 },
  { name: "South Africa", code: "+27", iso: "za", length: 9 },
  { name: "New Zealand", code: "+64", iso: "nz", length: 9 },
  { name: "Malaysia", code: "+60", iso: "my", length: 9 },
  { name: "Indonesia", code: "+62", iso: "id", length: 11 },
  { name: "Saudi Arabia", code: "+966", iso: "sa", length: 9 },
  { name: "Italy", code: "+39", iso: "it", length: 10 },
  { name: "Spain", code: "+34", iso: "es", length: 9 },
  { name: "Mexico", code: "+52", iso: "mx", length: 10 },
  { name: "South Korea", code: "+82", iso: "kr", length: 10 },
  { name: "Russia", code: "+7", iso: "ru", length: 10 },
  { name: "Netherlands", code: "+31", iso: "nl", length: 9 },
  { name: "Switzerland", code: "+41", iso: "ch", length: 9 },
  { name: "Sweden", code: "+46", iso: "se", length: 9 }
];
